"""
Test COPD Knowledge Base Loader (without OpenAI API)
Tests database structure with mock embeddings
"""
import asyncio
import sys
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import text

# Load environment variables
load_dotenv()

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from respira_ally.core.config import settings
from respira_ally.infrastructure.database.models.copd_knowledge_base import (
    COPDKnowledgeBaseModel,
)
from respira_ally.infrastructure.database.session import AsyncSessionLocal


async def test_load_knowledge_base():
    """
    Test loading COPD_QA.xlsx with mock embeddings
    """
    # 1. Read Excel file
    excel_path = Path(__file__).parent.parent / "data" / "COPD_QA.xlsx"
    print(f"📖 Reading {excel_path}...")
    df = pd.read_excel(excel_path)
    print(f"✅ Loaded {len(df)} rows")

    # 2. Connect to database
    async with AsyncSessionLocal() as session:
        # Clear existing data (using ORM to let SQLAlchemy handle schema)
        print("🗑️  Clearing existing knowledge base...")
        from sqlalchemy import delete
        await session.execute(delete(COPDKnowledgeBaseModel))
        await session.commit()
        print("✅ Cleared")

        # 3. Process first 3 rows only (test mode)
        test_rows = df.head(3)
        print(f"\n🔄 Processing {len(test_rows)} test entries...")

        for idx, row in test_rows.iterrows():
            category = row["類別"]
            question = row["問題（Q）"]
            answer = row["回答（A）"]
            keywords = row["關鍵詞"] if pd.notna(row["關鍵詞"]) else None
            notes = (
                row["注意事項 / 補充說明"]
                if pd.notna(row["注意事項 / 補充說明"])
                else None
            )

            # Create MOCK embedding (all zeros for testing)
            # In production, this would be generated by OpenAI
            mock_embedding = [0.0] * 1536

            print(f"  [{idx + 1}/{len(test_rows)}] Adding: {question[:50]}...")

            # Create database entry
            kb_entry = COPDKnowledgeBaseModel(
                category=category,
                question=question,
                answer=answer,
                keywords=keywords,
                notes=notes,
                embedding=mock_embedding,
            )

            session.add(kb_entry)

        # Commit
        await session.commit()
        print(f"\n✅ Successfully loaded {len(test_rows)} test entries!")

        # 4. Verify insertion using ORM
        from sqlalchemy import func, select

        result = await session.execute(
            select(func.count(COPDKnowledgeBaseModel.id))
        )
        count = result.scalar()
        print(f"📊 Total entries in database: {count}")

        # 5. Show inserted data
        result = await session.execute(
            select(COPDKnowledgeBaseModel)
            .order_by(COPDKnowledgeBaseModel.created_at)
            .limit(3)
        )
        entries = result.scalars().all()
        print(f"\n📝 Sample entries:")
        for entry in entries:
            print(f"  - [{entry.category}] {entry.question[:40]}...")
            print(f"    Answer: {entry.answer[:50]}...")


if __name__ == "__main__":
    print("🧪 Starting COPD Knowledge Base Test Loader...")
    print(f"📝 Using MOCK embeddings (all zeros)")
    print(f"🗄️  Database schema: {settings.get_db_schema()}\n")

    try:
        asyncio.run(test_load_knowledge_base())
        print("\n✨ Test completed!")
        print("\n💡 To load with real OpenAI embeddings:")
        print("   1. Set OPENAI_API_KEY in .env file")
        print("   2. Run: uv run python scripts/load_copd_knowledge.py")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
