"""
Alert Repository Implementation
Infrastructure Layer - Clean Architecture

Concrete implementation of AlertRepository interface using SQLAlchemy.
This class handles all database interactions for Alert entities.

Sprint 4: Alert System MVP
"""

from datetime import date
from uuid import UUID

from sqlalchemy import and_, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from respira_ally.domain.repositories.alert_repository import AlertRepository
from respira_ally.infrastructure.database.models.alert import AlertModel


class AlertRepositoryImpl(AlertRepository):
    """
    SQLAlchemy implementation of AlertRepository

    Uses async SQLAlchemy session for database operations.
    All methods are async to support FastAPI's async endpoints.
    """

    def __init__(self, db: AsyncSession):
        """
        Initialize repository with database session

        Args:
            db: SQLAlchemy async session
        """
        self.db = db

    async def create(self, alert: AlertModel) -> AlertModel:
        """
        Create a new alert record

        Args:
            alert: AlertModel instance to persist

        Returns:
            The created alert with database-generated fields

        Note:
            triggered_at, created_at, updated_at are auto-generated by database.
        """
        self.db.add(alert)
        await self.db.commit()
        await self.db.refresh(alert)
        return alert

    async def get_by_id(self, alert_id: UUID) -> AlertModel | None:
        """
        Retrieve alert by ID

        Args:
            alert_id: Alert UUID

        Returns:
            AlertModel if found, None otherwise
        """
        return await self.db.get(AlertModel, alert_id)

    async def list_by_patient(
        self,
        patient_id: UUID,
        skip: int = 0,
        limit: int = 20,
        # Filters
        alert_type: str | None = None,
        severity: str | None = None,
        status: str | None = None,
        start_date: date | None = None,
        end_date: date | None = None,
        sort_by: str = "triggered_at",
        sort_order: str = "desc",
    ) -> tuple[list[AlertModel], int]:
        """
        List alerts for a specific patient with filters and pagination

        Args:
            patient_id: Patient UUID
            skip: Number of records to skip
            limit: Maximum number of records to return
            alert_type: Filter by alert type
            severity: Filter by severity
            status: Filter by status
            start_date: Filter by triggered_at >= start_date
            end_date: Filter by triggered_at <= end_date
            sort_by: Sort field
            sort_order: Sort order (asc/desc)

        Returns:
            Tuple of (list of alerts, total count)
        """
        # Build base query conditions
        conditions = [AlertModel.patient_id == patient_id]

        # Apply filters
        if alert_type:
            conditions.append(AlertModel.alert_type == alert_type)
        if severity:
            conditions.append(AlertModel.severity == severity)
        if status:
            conditions.append(AlertModel.status == status)
        if start_date:
            conditions.append(AlertModel.triggered_at >= start_date)
        if end_date:
            conditions.append(AlertModel.triggered_at <= end_date)

        # Build base query with all conditions
        base_query = select(AlertModel).where(and_(*conditions))

        # Get total count
        count_query = select(func.count()).select_from(base_query.subquery())
        count_result = await self.db.execute(count_query)
        total = count_result.scalar() or 0

        # Apply sorting
        if sort_by == "triggered_at":
            order_column = AlertModel.triggered_at
        elif sort_by == "severity":
            # Sort by severity enum order: CRITICAL > HIGH > MEDIUM > LOW
            # Map to numeric values for sorting
            order_column = AlertModel.severity
        elif sort_by == "created_at":
            order_column = AlertModel.created_at
        else:  # default: alert_id (UUIDs have timestamp component)
            order_column = AlertModel.alert_id

        # Apply sort order
        if sort_order == "asc":
            order_clause = order_column.asc()
        else:
            order_clause = order_column.desc()

        # Get paginated results
        query = base_query.offset(skip).limit(limit).order_by(order_clause)
        result = await self.db.execute(query)
        alerts = list(result.scalars().all())

        return alerts, total

    async def count_active_by_patient(self, patient_id: UUID) -> int:
        """
        Count active alerts for a patient

        Args:
            patient_id: Patient UUID

        Returns:
            Number of active alerts
        """
        query = select(func.count()).where(
            and_(
                AlertModel.patient_id == patient_id,
                AlertModel.status == "ACTIVE",
            )
        )
        result = await self.db.execute(query)
        return result.scalar() or 0

    async def exists(self, alert_id: UUID) -> bool:
        """
        Check if alert exists

        Args:
            alert_id: Alert UUID

        Returns:
            True if alert exists, False otherwise
        """
        query = select(func.count()).where(AlertModel.alert_id == alert_id)
        result = await self.db.execute(query)
        count = result.scalar()
        return count > 0
