"""
Task Repository Implementation
Infrastructure Layer - Clean Architecture

Concrete implementation of ITaskRepository interface using SQLAlchemy.
This class handles all database interactions for Task entities.

Sprint 5: Task Management System - Phase B2
"""

from datetime import datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import and_, func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from respira_ally.domain.entities.task import Task, TaskPriority, TaskStatus, TaskType
from respira_ally.domain.repositories.i_task_repository import ITaskRepository
from respira_ally.infrastructure.database.models.task import TaskModel


class TaskRepositoryImpl(ITaskRepository):
    """
    SQLAlchemy implementation of ITaskRepository

    Responsibilities:
    - Convert between Task entity (domain) and TaskModel (infrastructure)
    - Handle all database CRUD operations for tasks
    - Support filtering, pagination, and sorting
    - Generate task statistics and reports

    Uses async SQLAlchemy session for database operations.
    All methods are async to support FastAPI's async endpoints.
    """

    def __init__(self, db: AsyncSession):
        """
        Initialize repository with database session

        Args:
            db: SQLAlchemy async session
        """
        self.db = db

    # ========== Converter Methods ==========

    @staticmethod
    def _to_entity(model: TaskModel) -> Task:
        """
        Convert TaskModel (infrastructure) to Task entity (domain)

        Args:
            model: TaskModel instance from database

        Returns:
            Task entity with business logic
        """
        return Task(
            task_id=model.task_id,
            title=model.title,
            description=model.description,
            priority=TaskPriority(model.priority),
            status=TaskStatus(model.status),
            task_type=TaskType(model.task_type),
            patient_id=model.patient_id,
            assigned_to=model.assigned_to,
            related_alert_id=model.related_alert_id,
            created_at=model.created_at,
            updated_at=model.updated_at,
            due_date=model.due_date,
            completed_at=model.completed_at,
            task_metadata=model.task_metadata or {},
        )

    @staticmethod
    def _to_model(entity: Task) -> TaskModel:
        """
        Convert Task entity (domain) to TaskModel (infrastructure)

        Args:
            entity: Task entity

        Returns:
            TaskModel for database persistence
        """
        return TaskModel(
            task_id=entity.task_id,
            title=entity.title,
            description=entity.description,
            priority=entity.priority.value,
            status=entity.status.value,
            task_type=entity.task_type.value,
            patient_id=entity.patient_id,
            assigned_to=entity.assigned_to,
            related_alert_id=entity.related_alert_id,
            created_at=entity.created_at,
            updated_at=entity.updated_at,
            due_date=entity.due_date,
            completed_at=entity.completed_at,
            task_metadata=entity.task_metadata,
        )

    # ========== CRUD Operations ==========

    async def create(self, task: Task) -> Task:
        """
        Create a new task

        Args:
            task: Task entity to create

        Returns:
            Created task with generated task_id and timestamps

        Note:
            created_at, updated_at are auto-generated by database.
        """
        model = self._to_model(task)
        self.db.add(model)
        await self.db.commit()
        await self.db.refresh(model)
        return self._to_entity(model)

    async def get_by_id(self, task_id: UUID) -> Optional[Task]:
        """
        Get task by ID

        Args:
            task_id: Task UUID

        Returns:
            Task entity if found, None otherwise
        """
        model = await self.db.get(TaskModel, task_id)
        return self._to_entity(model) if model else None

    async def update(self, task: Task) -> Task:
        """
        Update an existing task

        Args:
            task: Task entity with updated values

        Returns:
            Updated task entity

        Raises:
            ValueError: If task not found
        """
        model = await self.db.get(TaskModel, task.task_id)
        if not model:
            raise ValueError(f"Task {task.task_id} not found")

        # Update fields
        model.title = task.title
        model.description = task.description
        model.priority = task.priority.value
        model.status = task.status.value
        model.task_type = task.task_type.value
        model.assigned_to = task.assigned_to
        model.due_date = task.due_date
        model.completed_at = task.completed_at
        model.task_metadata = task.metadata
        model.updated_at = datetime.utcnow()

        await self.db.commit()
        await self.db.refresh(model)
        return self._to_entity(model)

    async def delete(self, task_id: UUID) -> bool:
        """
        Delete a task (hard delete)

        Args:
            task_id: Task UUID

        Returns:
            True if deleted, False if not found
        """
        model = await self.db.get(TaskModel, task_id)
        if not model:
            return False

        await self.db.delete(model)
        await self.db.commit()
        return True

    # ========== Query Operations ==========

    async def list_by_patient(
        self,
        patient_id: UUID,
        status: Optional[TaskStatus] = None,
        priority: Optional[TaskPriority] = None,
        task_type: Optional[TaskType] = None,
        page: int = 0,
        page_size: int = 20,
    ) -> tuple[list[Task], int]:
        """
        List tasks for a specific patient with filtering and pagination

        Args:
            patient_id: Patient UUID
            status: Filter by status
            priority: Filter by priority
            task_type: Filter by type
            page: Page number (0-based)
            page_size: Number of tasks per page

        Returns:
            Tuple of (list of tasks, total count)
        """
        # Build base query conditions
        conditions = [TaskModel.patient_id == patient_id]

        # Apply filters
        if status:
            conditions.append(TaskModel.status == status.value)
        if priority:
            conditions.append(TaskModel.priority == priority.value)
        if task_type:
            conditions.append(TaskModel.task_type == task_type.value)

        # Build base query
        base_query = select(TaskModel).where(and_(*conditions))

        # Get total count
        count_query = select(func.count()).select_from(base_query.subquery())
        count_result = await self.db.execute(count_query)
        total = count_result.scalar() or 0

        # Get paginated results (sorted by created_at desc)
        query = (
            base_query.offset(page * page_size)
            .limit(page_size)
            .order_by(TaskModel.created_at.desc())
        )
        result = await self.db.execute(query)
        models = list(result.scalars().all())

        return [self._to_entity(m) for m in models], total

    async def list_by_therapist(
        self,
        therapist_id: UUID,
        status: Optional[TaskStatus] = None,
        priority: Optional[TaskPriority] = None,
        include_unassigned: bool = False,
        page: int = 0,
        page_size: int = 20,
    ) -> tuple[list[Task], int]:
        """
        List tasks assigned to a specific therapist with filtering

        Args:
            therapist_id: Therapist UUID
            status: Filter by status
            priority: Filter by priority
            include_unassigned: Include unassigned tasks
            page: Page number (0-based)
            page_size: Number of tasks per page

        Returns:
            Tuple of (list of tasks, total count)
        """
        # Build base query conditions
        if include_unassigned:
            conditions = [
                or_(
                    TaskModel.assigned_to == therapist_id,
                    TaskModel.assigned_to.is_(None),
                )
            ]
        else:
            conditions = [TaskModel.assigned_to == therapist_id]

        # Apply filters
        if status:
            conditions.append(TaskModel.status == status.value)
        if priority:
            conditions.append(TaskModel.priority == priority.value)

        # Build base query
        base_query = select(TaskModel).where(and_(*conditions))

        # Get total count
        count_query = select(func.count()).select_from(base_query.subquery())
        count_result = await self.db.execute(count_query)
        total = count_result.scalar() or 0

        # Get paginated results (sorted by priority and created_at)
        query = (
            base_query.offset(page * page_size)
            .limit(page_size)
            .order_by(
                TaskModel.priority.desc(),  # CRITICAL > HIGH > MEDIUM > LOW
                TaskModel.created_at.desc(),
            )
        )
        result = await self.db.execute(query)
        models = list(result.scalars().all())

        return [self._to_entity(m) for m in models], total

    async def list_by_alert(self, alert_id: UUID) -> list[Task]:
        """
        Get all tasks related to a specific alert

        Args:
            alert_id: Alert UUID

        Returns:
            List of tasks
        """
        query = select(TaskModel).where(TaskModel.related_alert_id == alert_id)
        result = await self.db.execute(query)
        models = list(result.scalars().all())
        return [self._to_entity(m) for m in models]

    async def get_overdue_tasks(
        self,
        as_of: Optional[datetime] = None,
        therapist_id: Optional[UUID] = None,
    ) -> list[Task]:
        """
        Get all overdue tasks

        Args:
            as_of: Check overdue as of this datetime (default: now)
            therapist_id: Filter by therapist (optional)

        Returns:
            List of overdue tasks sorted by due_date
        """
        if as_of is None:
            as_of = datetime.utcnow()

        # Build conditions: due_date < as_of AND status NOT IN (DONE, CANCELLED)
        conditions = [
            TaskModel.due_date < as_of,
            TaskModel.status.not_in([TaskStatus.DONE.value, TaskStatus.CANCELLED.value]),
        ]

        if therapist_id:
            conditions.append(TaskModel.assigned_to == therapist_id)

        query = (
            select(TaskModel)
            .where(and_(*conditions))
            .order_by(TaskModel.due_date.asc())
        )
        result = await self.db.execute(query)
        models = list(result.scalars().all())
        return [self._to_entity(m) for m in models]

    async def get_task_statistics(
        self,
        therapist_id: Optional[UUID] = None,
        patient_id: Optional[UUID] = None,
    ) -> dict:
        """
        Get task statistics (counts by status, priority, etc.)

        Args:
            therapist_id: Filter by therapist (optional)
            patient_id: Filter by patient (optional)

        Returns:
            Dictionary with task statistics:
            {
                "total": int,
                "by_status": {"TODO": int, "IN_PROGRESS": int, ...},
                "by_priority": {"CRITICAL": int, "HIGH": int, ...},
                "overdue": int,
            }
        """
        # Build base conditions
        conditions = []
        if therapist_id:
            conditions.append(TaskModel.assigned_to == therapist_id)
        if patient_id:
            conditions.append(TaskModel.patient_id == patient_id)

        base_query = select(TaskModel)
        if conditions:
            base_query = base_query.where(and_(*conditions))

        # Get all tasks
        result = await self.db.execute(base_query)
        models = list(result.scalars().all())

        # Calculate statistics
        stats = {
            "total": len(models),
            "by_status": {status.value: 0 for status in TaskStatus},
            "by_priority": {priority.value: 0 for priority in TaskPriority},
            "overdue": 0,
        }

        now = datetime.utcnow()
        for model in models:
            # Count by status
            stats["by_status"][model.status] += 1

            # Count by priority
            stats["by_priority"][model.priority] += 1

            # Count overdue
            if (
                model.due_date
                and model.due_date < now
                and model.status
                not in [TaskStatus.DONE.value, TaskStatus.CANCELLED.value]
            ):
                stats["overdue"] += 1

        return stats
